name: Deploy to GitHub page

on:
  push:
    branches:
      - master

env:
  CI: true
  yarn-cache-name: yarn-cache-1
  yarn-cache-path: .yarn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Use or update Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ env.yarn-cache-path }}
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ env.yarn-cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn --cache-folder=${{ env.yarn-cache-path }} install --frozen-lockfile

      - name: Build
        run: yarn --cache-folder=${{ env.yarn-cache-path }} run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/app
